motsupot/katekyoshi-kun

frontend/index.html
frontend/src/background/index.ts
frontend/src/page/Page.tsx
frontend/src/page/index.tsx
frontend/src/popup/index.ts

選択中のテキストをポップアップ、新規タブに表示する

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/constants.ts
frontend/src/popup/Popup.tsx
frontend/vite.config.background.mts
frontend/vite.config.content.mts
frontend/vite.config.page.mts
frontend/vite.config.popup.mts
frontend/vite.config.sidepanel.mts

`.env` ファイルに
```
VITE_API_HOST=https://...
```
のようにセットしてください（ `/predict` ）は入れてはいけない

環境変数で API のホストを設定

---

frontend/src/background/index.ts
frontend/src/content/index.ts
frontend/src/sidepanel/SidePanel.tsx
frontend/src/sidepanel/index.tsx

サイドパネルに要約ボタン設置

---

frontend/src/sidepanel/SidePanel.tsx

サイドパネルから質問できるようにする

---

backend/app/main.py

画像のように保存する。
questionは受け取った質問、
answerはGeminiの回答、
一旦、ユーザーは固定してます。

質問と回答をDBに保存（ユーザーは固定）

---

.vscode/settings.json
frontend/src/background/index.ts
frontend/src/constants.ts
frontend/src/page/Page.tsx
frontend/src/page/index.tsx
frontend/src/popup/Popup.tsx
frontend/src/shared/components/SortableList/SortableList.tsx
frontend/src/shared/components/SortableList/components/SortableItem/SortableItem.css
frontend/src/shared/components/SortableList/components/SortableItem/SortableItem.tsx
frontend/src/shared/components/SortableList/components/SortableOverlay/SortableOverlay.tsx
frontend/src/shared/hooks/index.ts
frontend/src/sidepanel/components/Question.tsx
frontend/src/sidepanel/components/Summary.tsx
frontend/src/sidepanel/components/index.tsx
frontend/src/types.ts

参考
https://zenn.dev/cordelia/articles/c5a8a68444e7d8

prettier 追加（コード整形）

---

.vscode/settings.json
frontend/src/background/index.ts
frontend/src/constants.ts
frontend/src/page/Page.tsx
frontend/src/page/index.tsx
frontend/src/popup/Popup.tsx
frontend/src/shared/components/SortableList/SortableList.tsx
frontend/src/shared/components/SortableList/components/SortableItem/SortableItem.css
frontend/src/shared/components/SortableList/components/SortableItem/SortableItem.tsx
frontend/src/shared/components/SortableList/components/SortableOverlay/SortableOverlay.tsx
frontend/src/shared/hooks/index.ts
frontend/src/sidepanel/SidePanel.tsx
frontend/src/sidepanel/components/Question.tsx
frontend/src/sidepanel/components/Summary.tsx
frontend/src/sidepanel/components/index.tsx
frontend/src/types.ts

サイドパネル上での質問を、会話形式にできるようにする（過去会話を記憶した状態）

---

backend/.env.example
backend/BACKEND_SETUP.md
backend/app/main.py
frontend/src/sidepanel/components/Question.tsx
frontend/src/sidepanel/components/Summary.tsx

要約と質問はDB上区別できるようにする

---

frontend/src/shared/components/SortableList/components/SortableItem/SortableItem.css
frontend/src/sidepanel/components/Question.tsx
frontend/src/sidepanel/components/base.tsx

・質問欄の初期データとして「アシスタント:」が入ってしまっていた問題の解決
・無駄な余白削除

サイドパネルのUI改善

---

backend/app/main.py
frontend/src/page/Page.tsx
frontend/src/page/index.tsx
frontend/src/shared/hooks/index.ts

pageに、自分が送った質問一覧が表示される

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/sidepanel/components/Quiz/Feedback.tsx
frontend/src/sidepanel/components/Quiz/Question.tsx
frontend/src/sidepanel/components/Summary.tsx

Markdown 形式の出力をレンダリング

---

frontend/sidepanel.html
frontend/src/sidepanel/SidePanel.tsx

サイドパネルの横幅に合わせて表示を切り替える

---

backend/app/db.py
backend/app/main.py
backend/app/model.py
backend/app/predict/__init__.py
backend/app/predict/router.py
frontend/src/sidepanel/components/Question.tsx
frontend/src/sidepanel/components/Quiz/Quiz.tsx
frontend/src/sidepanel/components/Summary.tsx

NEXT: クライアントサイドでプロンプト生成しているのをサーバに寄せる。

機能ごとにエンドポイントを分離する

---

frontend/src/sidepanel/components/Question.tsx
frontend/src/sidepanel/components/Quiz/Quiz.tsx
frontend/src/sidepanel/components/Summary.tsx

サイドパネルの初期表示改善

---

backend/app/bookmarks/router.py
backend/app/model.py
backend/app/predict/router.py
frontend/src/shared/hooks/index.ts
frontend/src/sidepanel/components/Summary.tsx

https://github.com/motsupot/katekyoshi-kun/issues/30

要約のブックマーク機能追加

---

backend/app/main.py
backend/app/model.py

タイムスタンプをオプショナルに

---

backend/app/bookmarks/router.py
backend/app/model.py
frontend/src/page/Bookmarks.tsx
frontend/src/page/Page.tsx

pageにてブックマークサマリ一覧を取得

---

.gitignore
frontend/.storybook/main.ts
frontend/.storybook/preview.ts
frontend/package.json
frontend/pnpm-lock.yaml
frontend/sidepanel.html
frontend/src/sidepanel/components/Bookmark.css
frontend/src/sidepanel/components/Bookmark.stories.tsx
frontend/src/sidepanel/components/Bookmark.tsx
frontend/src/sidepanel/components/Summary.stories.tsx
frontend/src/sidepanel/components/Summary.tsx
frontend/src/sidepanel/components/base.tsx
frontend/src/sidepanel/sidepanel.css

ブックマークのアイコンを設置

---

frontend/src/sidepanel/components/Quiz/Feedback.tsx
frontend/src/sidepanel/components/Quiz/Question.tsx

クイズの重複表記を削除

---

backend/app/bookmarks/router.py
backend/app/main.py
backend/app/model.py
backend/app/predict/router.py
frontend/package.json
frontend/src/sidepanel/components/Quiz/Quiz.stories.tsx
frontend/src/sidepanel/components/Quiz/Quiz.tsx
frontend/src/sidepanel/components/Summary.tsx

クイズカードにブックマーク追加

---

backend/app/bookmarks/router.py
backend/app/model.py
frontend/src/shared/hooks/index.ts
frontend/src/sidepanel/components/Bookmark.stories.tsx
frontend/src/sidepanel/components/Bookmark.tsx
frontend/src/sidepanel/components/Quiz/Quiz.tsx
frontend/src/sidepanel/components/Summary.tsx

ブックマーク削除機能

---

.github/workflows/deploy.yml

tag nameを修正

---

frontend/src/sidepanel/sidepanel.css

サイドパネルが見切れるのを修正
